# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='sides',
            field=models.ManyToManyField(blank=True, null=True, related_name='_recipe_sides_+', to='meals.Recipe'),
        ),
    ]
