# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 15:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_recipe_sides'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='sides',
        ),
    ]
